from sqlalchemy.orm import Session
from passlib.context import CryptContext
import models
from routers.auth import get_password_hash

def seed_db(db: Session):
    if db.query(models.Product).first():
        return
    
    admin = models.User(
        name="Admin User",
        email="admin@quickbite.com",
        password_hash=get_password_hash("admin123"),
        role="admin",
        phone="+15550000000",
        address="123 Admin St, City"
    )
    db.add(admin)

    dummy_products = [
        # BURGERS
        models.Product(name_en="Classic Beef Burger", name_ar="برجر لحم كلاسيكي", description_en="Juicy 150g beef patty with cheddar cheese, lettuce, tomato.", description_ar="شريحة لحم بقري 150 جم مع جبنة الشيدر، الخس والطماطم.", price=150.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Double Smash Burger", name_ar="دبل سماش برجر", description_en="Two smashed beef patties, double cheese, caramelized onions.", description_ar="شريحتين من اللحم المهروس، جبن مضاعف، بصل مكرمل.", price=220.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Mushroom Swiss Burger", name_ar="برجر ماشروم سويس", description_en="Beef patty topped with sautéed mushrooms and Swiss cheese.", description_ar="شريحة لحم مغطاة بالفطر السوتيه والجبن السويسري.", price=190.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Spicy Jalapeno Burger", name_ar="برجر هالبينو حار", description_en="Beef patty, pepper jack cheese, jalapenos, and spicy mayo.", description_ar="لحم بقري، جبن بيبر جاك، هالبينو، ومايونيز حار.", price=175.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="BBQ Bacon Burger", name_ar="برجر بيكون باربكيو", description_en="Beef patty, beef bacon, onion rings, cheddar, and BBQ sauce.", description_ar="لحم بقري، بيكون بقري، حلقات بصل، شيدر، وصوص باربكيو.", price=210.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Chicken Fillet Burger", name_ar="برجر دجاج فيليه", description_en="Crispy chicken fillet, lettuce, pickles, and mayo.", description_ar="فيليه دجاج مقرمش، خس، مخلل، ومايونيز.", price=160.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Burgers"),
        models.Product(name_en="Truffle Burger", name_ar="برجر ترافل", description_en="Premium beef patty with truffle mayo and arugula.", description_ar="شريحة لحم ممتازة مع مايونيز الترافل والجرجير.", price=280.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Vegan Beyond Burger", name_ar="برجر نباتي", description_en="Plant-based patty with vegan cheese and fresh veggies.", description_ar="شريحة نباتية مع جبن نباتي وخضروات طازجة.", price=250.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Mini Sliders (3 pcs)", name_ar="سلايدرز ميني (3 قطع)", description_en="Three mini beef sliders with cheese and ketchup.", description_ar="ثلاثة سلايدرز لحم ميني مع الجبن والكاتشب.", price=200.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),
        models.Product(name_en="Tower Burger", name_ar="تاور برجر", description_en="Triple beef patties, triple cheese, ultimate hunger killer.", description_ar="ثلاث شرائح لحم، جبن ثلاثي، قاهر الجوع.", price=350.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuBL1UOfRCBA7eVVZoY4K9vq36dKKbtPFLbufx25aRrZ6fElkGUtstk6wgbjjWNbh5IF9xNQlGqxNKlEdyhlAwXgKW7EF0upEBLMJraZQv9h4c6HBi7YoZQPOtgBV_eLcFyUrfq-LD5Z-svIXBsnP_VsZmMw7awiI8gubBj0LBPH_pIDjjkWpA_hP7UIHvvTMCRpgX4F-vYD6Qgrug4tQ0M7gsG4gyHH_Rrmvw2bWIspq304-j9rmDtgEgJtu4m_vm-YzCXqZjpJ7rk", category="Burgers"),

        # PIZZA
        models.Product(name_en="Margherita Pizza", name_ar="بيتزا مارجريتا", description_en="Classic tomato sauce, fresh mozzarella, and basil.", description_ar="صلصة الطماطم الكلاسيكية، الموزاريلا الطازجة، والريحان.", price=180.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Pepperoni Pizza", name_ar="بيتزا بيبروني", description_en="Large thin crust pizza loaded with premium pepperoni slices.", description_ar="بيتزا رقيقة كبيرة مليئة بشرائح البيبروني الممتازة.", price=220.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="BBQ Chicken Pizza", name_ar="بيتزا دجاج باربكيو", description_en="Grilled chicken, red onions, cilantro, and BBQ sauce.", description_ar="دجاج مشوي، بصل أحمر، كزبرة، وصوص الباربكيو.", price=240.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Vegetarian Pizza", name_ar="بيتزا نباتية", description_en="Bell peppers, mushrooms, onions, olives, and tomatoes.", description_ar="فلفل، فطر، بصل، زيتون، وطماطم.", price=200.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Four Cheese Pizza", name_ar="بيتزا 4 أجبان", description_en="Mozzarella, cheddar, parmesan, and blue cheese.", description_ar="موزاريلا، شيدر، بارميزان، وجبنة زرقاء.", price=260.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Seafood Pizza", name_ar="بيتزا فواكه البحر", description_en="Shrimp, calamari, garlic, and fresh mozzarella.", description_ar="جمبري، كاليماري، ثوم، وموزاريلا طازجة.", price=320.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Hawaiian Pizza", name_ar="بيتزا هاواي", description_en="Pineapple chunks, smoked turkey, and mozzarella.", description_ar="قطع أناناس، ديك رومي مدخن، وموزاريلا.", price=210.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Meat Lovers Pizza", name_ar="بيتزا عشاق اللحوم", description_en="Pepperoni, sausage, ground beef, and smoked turkey.", description_ar="بيبروني، سجق، لحم مفروم، ورومي مدخن.", price=290.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Chicken Ranch Pizza", name_ar="بيتزا تشيكن رانش", description_en="Chicken cubes, mushrooms, and creamy ranch sauce.", description_ar="مكعبات دجاج، فطر، وصوص الرانش الكريمي.", price=250.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),
        models.Product(name_en="Spicy Oriental Pizza", name_ar="بيتزا شرقية حارة", description_en="Oriental sausage, jalapenos, and mixed cheese.", description_ar="سجق شرقي، هالبينو، وجبن مشكل.", price=230.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuANkva8p0WH_aPzPVGkL1Xj8rnBZ0S_qk83Pp2KqjTG8p7ur04Nn89Qp9k7j1IX7y4x6n3YNv_Jik7X3EQ2EbARBFJO2AE8fKGK6bEtQk5G0M8ZkPKkajMqDfjFmhj0cgDPeqOCqK13EBdSQNzvNBwuT-xcbbRoZSnAz6fBKGiaA3b_kfzuRqRS69TJQ-Ac1RuDmU4UVgf5VXiubdtchCLV4KEIexyC2CWN65ND4K2aI6hB06XefrgasQHopDKjTgVa3SHJJggkR44", category="Pizza"),

        # CHICKEN
        models.Product(name_en="Crispy Chicken Meal (3 pcs)", name_ar="وجبة دجاج مقرمش (3 قطع)", description_en="3 pieces of crispy fried chicken with fries and coleslaw.", description_ar="3 قطع من الدجاج المقرمش مع بطاطس وكولسلو.", price=180.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Strips Meal (5 pcs)", name_ar="وجبة استربس دجاج (5 قطع)", description_en="5 spicy chicken strips with honey mustard dip and fries.", description_ar="5 قطع استربس دجاج حارة مع صوص المستردة بالعسل وبطاطس.", price=160.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Family Bucket (12 pcs)", name_ar="باكت عائلي (12 قطعة)", description_en="12 pcs of fried chicken, family fries, large coleslaw.", description_ar="12 قطعة دجاج مقلي، بطاطس عائلية، وكولسلو حجم كبير.", price=550.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Grilled Chicken Half", name_ar="نصف دجاجة مشوية", description_en="Half chicken grilled on charcoal with rice and garlic dip.", description_ar="نصف دجاجة مشوية على الفحم مع أرز وثومية.", price=170.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Wings (8 pcs)", name_ar="أجنحة دجاج (8 قطع)", description_en="Buffalo or BBQ glazed chicken wings with ranch dip.", description_ar="أجنحة دجاج بصوص البافلو أو الباربكيو مع صوص الرانش.", price=130.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Nuggets (9 pcs)", name_ar="ناجتس دجاج (9 قطع)", description_en="Crispy chicken nuggets, perfect for a quick snack.", description_ar="ناجتس دجاج مقرمش، مثالي لوجبة خفيفة سريعة.", price=110.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Shawarma Meal", name_ar="وجبة شاورما دجاج", description_en="Chicken shawarma with garlic dip, pickles, and fries.", description_ar="شاورما دجاج مع ثومية، مخلل، وبطاطس.", price=150.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Spicy Fried Chicken (2 pcs)", name_ar="دجاج مقلي حار (قطعتين)", description_en="2 pieces of our signature spicy fried chicken.", description_ar="قطعتين من الدجاج المقلي الحار المميز لدينا.", price=120.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Fajita Pan", name_ar="طاسة فاهيتا دجاج", description_en="Sizzling chicken fajita with colorful peppers and onions.", description_ar="فاهيتا دجاج ساخنة مع فلفل ملون وبصل.", price=190.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),
        models.Product(name_en="Chicken Popcorn", name_ar="بوب كورن دجاج", description_en="Bite-sized crispy chicken pieces.", description_ar="قطع دجاج مقرمشة بحجم اللقمة.", price=80.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuCqM1rYTtrcuqAvu7NZsMJroPbm83nM62-sRxV-F3L5o1BgQo16hB0hwzUloEX1WvqTx4-L4MXcEyuNum5H-DMgOlGS5rHlY36YiCbp__AlNGuA0JzGHzccAO1GyObCCRov3Ktc6iL10w_sWuWLZKCxuCBoW0ldtdlKLZqpG3ysEbv5UVWe760A62GzDsMpU1sOuzbpgCnskuEFQ3iIhUOMnOcCwYYALbxj_bEFLCBNRsNkH-qiKKTAcW7OAmyhAUJ5B3WRLVVYAVU", category="Chicken"),

        # KOSHARY
        models.Product(name_en="Authentic Koshary (Medium)", name_ar="كشري أصيل (وسط)", description_en="Traditional mix of rice, lentils, and pasta with tomato sauce.", description_ar="خليط تقليدي من الأرز، العدس، والمعكرونة مع صلصة الطماطم.", price=40.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Authentic Koshary (Large)", name_ar="كشري أصيل (كبير)", description_en="Large portion of traditional Koshary with extra onions.", description_ar="وجبة كبيرة من الكشري التقليدي مع بصل إضافي.", price=55.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Koshary with Liver", name_ar="كشري بالكبدة", description_en="Koshary topped with Alexandrian style liver.", description_ar="كشري يعلوه كبدة إسكندراني.", price=85.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Koshary with Shawarma", name_ar="كشري بالشاورما", description_en="Koshary topped with delicious chicken shawarma slices.", description_ar="كشري مغطى بشرائح شاورما الدجاج اللذيذة.", price=95.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Koshary with Minced Meat", name_ar="كشري باللحم المفروم", description_en="Classic koshary enhanced with spiced minced meat.", description_ar="كشري كلاسيكي معزز باللحم المفروم المتبل.", price=90.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Family Koshary Meal", name_ar="وجبة كشري عائلية", description_en="Huge portion of Koshary to feed 4 persons, with all sauces.", description_ar="وجبة ضخمة من الكشري تكفي 4 أشخاص، مع جميع الصلصات.", price=200.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Spicy Koshary (Fire)", name_ar="كشري حار جداً", description_en="Koshary with double chili sauce for the brave ones.", description_ar="كشري مع صلصة شطة مضاعفة للشجعان.", price=45.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Rice Pudding", name_ar="أرز باللبن", description_en="Classic creamy rice pudding dessert.", description_ar="حلوى الأرز باللبن الكريمية الكلاسيكية.", price=25.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Extra Tomato Sauce", name_ar="صلصة طماطم إضافية", description_en="A side of our signature tomato sauce.", description_ar="جانب من صلصة الطماطم المميزة لدينا.", price=10.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),
        models.Product(name_en="Extra Crispy Onions", name_ar="بصل مقرمش إضافي", description_en="More of the delicious crispy fried onions (Ward).", description_ar="المزيد من البصل المقلي المقرمش اللذيذ (الورد).", price=15.0, image_url="https://lh3.googleusercontent.com/aida-public/AB6AXuB3BID58Ye2l6iTqvXPhs0qcXf37uK9ROIuz439F2Swiyk7pS3trYbz7wbo3riJbXP1R0r-YAYGXfZDA2f0L1O8TuN_RSaXpe6yOc4NC0I4RLP_EhvO5SSeBSJxh-Q1rPQsT2B3fBIIoaVulmVSmLX7JA7zyo2vgjr5bdyCKIzYyOHQ4OvoKgX_LVntGeSTTRkET-U8RiWxOJHsH1cHbZbHYDtoBN8wrWE_LuecPjXL-5GBlxpvbW5gY822lvxZjHu_GC3fichAaxA", category="Koshary"),

        # DRINKS
        models.Product(name_en="Pepsi Can", name_ar="بيبسي كانز", description_en="Refreshing 330ml Pepsi can.", description_ar="كانز بيبسي 330 مل منعش.", price=20.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="7UP Can", name_ar="سفن أب كانز", description_en="Refreshing 330ml 7UP can.", description_ar="كانز سفن أب 330 مل منعش.", price=20.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Fresh Orange Juice", name_ar="عصير برتقال فريش", description_en="Freshly squeezed orange juice, no added sugar.", description_ar="عصير برتقال طازج، بدون سكر مضاف.", price=45.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Mango Juice", name_ar="عصير مانجو", description_en="Rich and thick pure mango juice.", description_ar="عصير مانجو غني ومكثف.", price=50.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Lemon Mint", name_ar="ليمون بالنعناع", description_en="Refreshing blended lemon and fresh mint.", description_ar="ليمون ونعناع طازج منعش.", price=40.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Mineral Water (Small)", name_ar="مياه معدنية (صغير)", description_en="600ml bottled mineral water.", description_ar="زجاجة مياه معدنية 600 مل.", price=10.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Mineral Water (Large)", name_ar="مياه معدنية (كبير)", description_en="1.5L bottled mineral water.", description_ar="زجاجة مياه معدنية 1.5 لتر.", price=15.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Iced Tea Peach", name_ar="آيس تي خوخ", description_en="Cold brewed tea with natural peach flavor.", description_ar="شاي بارد بنكهة الخوخ الطبيعية.", price=35.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Strawberry Smoothie", name_ar="سموثي فراولة", description_en="Icy blended strawberry smoothie.", description_ar="سموثي الفراولة المثلج.", price=55.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),
        models.Product(name_en="Classic Iced Coffee", name_ar="آيس كوفي كلاسيك", description_en="Chilled espresso with milk and ice.", description_ar="إسبريسو بارد مع الحليب والثلج.", price=60.0, image_url="https://images.unsplash.com/photo-1622483767028-3f66f32aef97", category="Drinks"),

        # DESSERTS
        models.Product(name_en="Chocolate Lava Cake", name_ar="مولتن كيك", description_en="Warm chocolate cake with a gooey molten center.", description_ar="كعكة شوكولاتة دافئة مع مركز سائل غني.", price=80.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Cheesecake Slice", name_ar="شريحة تشيز كيك", description_en="Classic New York style cheesecake with strawberry topping.", description_ar="تشيز كيك نيويورك الكلاسيكية مع صوص الفراولة.", price=95.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Om Ali", name_ar="أم علي", description_en="Traditional Egyptian bread pudding with nuts and cream.", description_ar="حلوى أم علي المصرية التقليدية بالمكسرات والقشطة.", price=60.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Brownies with Ice Cream", name_ar="براونيز مع آيس كريم", description_en="Fudgy chocolate brownie topped with vanilla ice cream.", description_ar="براونيز شوكولاتة غنية يعلوها آيس كريم فانيليا.", price=75.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Tiramisu", name_ar="تيراميسو", description_en="Classic Italian coffee-flavored dessert.", description_ar="حلوى إيطالية كلاسيكية بنكهة القهوة.", price=110.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Kunafa with Nutella", name_ar="كنافة بالنوتيلا", description_en="Crispy kunafa layered with rich Nutella chocolate.", description_ar="كنافة مقرمشة بطبقات من شوكولاتة النوتيلا الغنية.", price=85.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Kunafa with Mango", name_ar="كنافة بالمانجو", description_en="Crispy kunafa layered with cream and fresh mango cubes.", description_ar="كنافة مقرمشة بطبقات من الكريمة ومكعبات المانجو الطازجة.", price=90.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Fruit Salad", name_ar="سلطة فواكه", description_en="A mix of fresh seasonal fruits.", description_ar="مزيج من الفواكه الموسمية الطازجة.", price=45.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Vanilla Ice Cream (2 Scoops)", name_ar="آيس كريم فانيليا (بولتين)", description_en="Two scoops of rich vanilla bean ice cream.", description_ar="بولتين من آيس كريم الفانيليا الغني.", price=40.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts"),
        models.Product(name_en="Chocolate Ice Cream (2 Scoops)", name_ar="آيس كريم شوكولاتة (بولتين)", description_en="Two scoops of creamy chocolate ice cream.", description_ar="بولتين من آيس كريم الشوكولاتة الكريمي.", price=40.0, image_url="https://images.unsplash.com/photo-1551024506-0bccd828d307", category="Desserts")
    ]
    db.add_all(dummy_products)
    db.commit()
